sudo: required
services:
  - docker

before_install:
  - docker build -t mariov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mariov/docker-react npm run test -- --coverage

  # language: generic 